spring.datasource.url=jdbc:mysql://localhost:3306/clinica

# Nome do usu?rio do banco de dados
spring.datasource.username=root

# Senha do usu?rio do banco de dados
spring.datasource.password=

# Driver JDBC usado para conectar no MariaDB
# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialeto do banco, para o Hibernate gerar comandos SQL compat?veis com MariaDB
# spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Define o comportamento da estrutura do banco
# update = cria ou atualiza tabelas automaticamente sem apagar os dados
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL executados pela aplica??o
spring.jpa.show-sql=true

# Formata o SQL exibido no console para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true
